### ISSUE TITLE
Wrong/weird characters displayed on .fon (working Windows) version

### ISSUE THREAD

**Issue by diffficult** [NerdyPepper/scientifica#4]
Nice work on the font, using it right now on my laptop but specially on a couple of raspberry pi attached to small lcd screens that display various info.

Just checked you also made a .fon version that technically works on Windows systems and even though it's pretty much working no problems I'm getting a weird "ÿ" character instead of "❯" when using it with ConEmu as you can see on my screencap.

![scientifica_knack](https://user-images.githubusercontent.com/11413264/36190930-8e6ad052-1139-11e8-9b41-0ead4980f4d0.jpg)

The other font used is Knack NF which somehow has full support for every symbol I've seen so far.

Is this expected? Is it fixable?

**Comment by NerdyPepper** [comment]
Scientifica does include this character:  
https://0x0.st/sTcx.png

Looks like the `.fon` export did not include the entire character range, and hence defaulted to the last character U+00FF.

Should be fixed in the latest commit. Reopen the issue if not.

**Comment by diffficult** [comment]
@NerdyPepper thanks a lot for checking it, the issue persist, this probably is a deeper issue on how ConEmu handles terminal/command line and fonts on Windows, which after reading a bit is "hacky" to say the least. Other fonts like **DejaVu Sans Mono for Powerline** or **Hack** also seem to work just fine and do not fail to present all the characters and some other bitmap fonts turned to .fon like **lime** instead of a "ÿ" char they present a "4" instead.

Besides that the font works perfectly fine on linux so far.
