### ISSUE TITLE
Excessive right side bearings

### ISSUE THREAD

**Issue by dscorbett** [NerdyPepper/scientifica#47]
Many glyphs have excessive right side bearings. For example, here is “(Ă)”.
![(Ă)](https://user-images.githubusercontent.com/1124347/100545969-aa2da500-322c-11eb-8daa-e43ebbac7a8a.png)

**Comment by NerdyPepper** [comment]
Can you answer the following:

 - which variant of scientifica is being used here? (TTF, OTB or BDF)
 - which application are you using to render this screenshot?
 - which operating system are you using and how did you install the font?

**Comment by dscorbett** [comment]
This is the TTF. I used hb-view on macOS. I did not install the font.

**Comment by NerdyPepper** [comment]
Thanks for the info, I was able to reproduce this, should be fixed with the latest release (v2.2).

**Comment by dscorbett** [comment]
This issue still exists. There are still 592 glyphs that are too wide.
